//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeScaler) DeepCopyInto(out *PersistentVolumeScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeScaler.
func (in *PersistentVolumeScaler) DeepCopy() *PersistentVolumeScaler {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentVolumeScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeScalerList) DeepCopyInto(out *PersistentVolumeScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PersistentVolumeScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeScalerList.
func (in *PersistentVolumeScalerList) DeepCopy() *PersistentVolumeScalerList {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentVolumeScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeScalerSpec) DeepCopyInto(out *PersistentVolumeScalerSpec) {
	*out = *in
	if in.PVCRefName != nil {
		in, out := &in.PVCRefName, &out.PVCRefName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ScaleParameters = in.ScaleParameters
	if in.RestartPods != nil {
		in, out := &in.RestartPods, &out.RestartPods
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeScalerSpec.
func (in *PersistentVolumeScalerSpec) DeepCopy() *PersistentVolumeScalerSpec {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeScalerStatus) DeepCopyInto(out *PersistentVolumeScalerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeScalerStatus.
func (in *PersistentVolumeScalerStatus) DeepCopy() *PersistentVolumeScalerStatus {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleParameters) DeepCopyInto(out *ScaleParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleParameters.
func (in *ScaleParameters) DeepCopy() *ScaleParameters {
	if in == nil {
		return nil
	}
	out := new(ScaleParameters)
	in.DeepCopyInto(out)
	return out
}
