---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pvc.scaler.opstreelabs.in
  resources:
  - persistentvolumescalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pvc.scaler.opstreelabs.in
  resources:
  - persistentvolumescalers/finalizers
  verbs:
  - update
- apiGroups:
  - pvc.scaler.opstreelabs.in
  resources:
  - persistentvolumescalers/status
  verbs:
  - get
  - patch
  - update
